baseURL = "https://warehamw.github.io"
languageCode = "en-us"
title = "W. Callum Wareham"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000

[params]
  subtitle= "Undergraduate Student"
  interests="Computational Physics, Astrophysics, Physics Education"
  cv_name= "CV_Callum_Wareham_a.pdf"
  blog="http://myblog.edu"

[[params.affilation]]
  name = "University of Guelph"
  position = "Undergraduate Student"
  contact = "warehamw@uoguelph.ca"

[[params.affilation]]
  name = "Siegel Astrophysics Group"
  position = "Student Research Assistant"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/warehamw"


[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/wcallumwareham"


[[params.introduction.paragraph]]
  text="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
	 Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Integer feugiat scelerisque varius morbi enim.
	  A diam maecenas sed enim ut sem viverra. Orci eu lobortis elementum nibh tellus.
		Egestas sed sed risus pretium quam vulputate dignissim suspendisse in.
		Accumsan sit amet nulla facilisi morbi tempus iaculis urna. Condimentum lacinia quis vel eros donec.
   """
[[params.introduction.paragraph]]
  text=""" Pellentesque nec nam aliquam sem et tortor consequat id porta.
	Viverra suspendisse potenti nullam ac. Leo vel orci porta non pulvinar neque laoreet.
	Nulla facilisi nullam vehicula ipsum a arcu. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse.
	Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Dui sapien eget mi proin sed libero.
	Quam pellentesque nec nam aliquam sem et tortor consequat id. Aliquet lectus proin nibh nisl.
  """

[[params.awards]]
	[[params.awards.award]]
		name = "James L. Hunt Scholarship"
		year = "2020-2021"
		description = "Awarded to a third-year physics major who has completed a minimum of 10 credits and who has the highest cumulative average over 80%."
		award_page = "https://www.physics.uoguelph.ca/james-l-hunt-scholarship"
	
	[[params.awards.award]]
		name = "Copernicus Scholarship in Physics"
		year = "2020"
		description = "Awarded to the three students achieving the highest combined average in PHYS\\*2330 (Electricity and Magnetism I) and PHYS\\*2240 (Thermal Physics) in the previous academic semester."
		award_page = "https://www.physics.uoguelph.ca/copernicus-scholarships-physics"

	[[params.awards.award]]
		name = "College of Biological Sciences Dean’s Scholarship"
		year = "2020"
		description = "Awarded to those students demonstrating a high level of academic achievement. At the time that I was considered for this award, I was enrolled in the Biochemistry program through the College of Biological Sciences."
		award_page = "https://www.uoguelph.ca/ada-cbs/current-undergraduates/awards-and-financial-information/deans-scholarships"

[[params.projects]]
	[[params.projects.project]]
		name = "Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor"
		description  = "Enim facilisis gravida neque convallis a. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse.Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor. In nisl nisi scelerisque eu ultrices vitae auctor."
		project_page = "https://myprojecthomepage.com"
		code_link = "https://coderepo.com"
		blog_link = "https://ablogpost.com"

 [[params.projects.project]]
		name = "In nisl nisi scelerisque eu ultrices vitae auctor"
		description  = ""
		project_page = "https://myprojecthomepage.com"
		code_link = "https://coderepo.com"
		blog_link = ""

 [[params.projects.project]]
		name = "Integer eget aliquet nibh praesent tristique magna"
		description  = ""
		project_page = "https://myprojecthomepage.com"
		code_link = ""
		blog_link = "https://ablogpost.com"

[[params.publications]]
  year="Preprint"

  [[params.publications.paper]]
    name = "Enim nunc faucibus a pellentesque sit amet porttitor"
    authors = "Ana Alvardo, William Worthley, __Hadi Sinaee__"
    dest  = "Helga Zita Journal"
    link = "https://mypaperishere.com"
    code_link = "https://thecoderepo.com"
    blog_link = "https://myblogaboutit.com"

[[params.publications]]
  year="2019"

  [[params.publications.paper]]
		name = "Feugiat sed lectus vestibulum mattis ullamcorper velit sed"
		authors = "Caroll Comes, __Hadi Sinaee__"
		dest  = "Udo Madhu Journal"
		link = "https://mypaperishere.com"
		code_link = "https://thecoderepo.com"
		blog_link = ""
