baseURL = "https://warehamw.github.io"
languageCode = "en-us"
title = "W. Callum Wareham"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000

[params]
  subtitle= "Undergraduate Student"
  interests="Computational Physics, Astrophysics, Physics Education"
  cv_name= "CV_Callum_Wareham_a.pdf"
  blog="http://myblog.edu"

[[params.affilation]]
  name = "University of Guelph"
  position = "Undergraduate Student"
  contact = "warehamw@uoguelph.ca | calwareham99@gmail.com"

[[params.affilation]]
  name = "Siegel Astrophysics Group"
  position = "Student Research Assistant"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/warehamw"


[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/wcallumwareham"


[[params.introduction.paragraph]]
  text="""Hi there! If you've just stumbled across my page, you'll find that it's pretty incomplete at the moment - broken links everywhere!
  However, this page is **under construction**, and will house information about me and hopefully a small blog, eventually.
  In the meantime, a little about me; you can check out my CV at the link above, if you'd like!
   """
[[params.introduction.paragraph]]
  text=""" I'm currently enrolled in an undergraduate Physics program at the University of Guelph, where I'm trying to learn the foundational skills of being a scientist.
  I chose physics because I was interested in all branches of science, and I felt that physics was the best place to specialize, if I had to do so. 
  I've since fallen fully for physics, and want to make physics research my career.
  I've been lucky enough to have some opportunities to be involved with some research throughout my undergrad, which have even further sparked my interest in scientific research!
  """

[[params.introduction.paragraph]]
  text=""" Below, you'll find some more information about my (short) academic career. Please feel free to get in touch with me at my email address above or by sending me a message on LinkedIn.
  Thanks for visiting!
  """
[[params.awards]]
	[[params.awards.award]]
		name = "James L. Hunt Scholarship"
		year = "2020-2021"
		description = "Awarded to a third-year physics major who has completed a minimum of 10 credits and who has the highest cumulative average over 80%."
		award_page = "https://www.physics.uoguelph.ca/james-l-hunt-scholarship"
	
	[[params.awards.award]]
		name = "Copernicus Scholarship in Physics"
		year = "2020"
		description = "Awarded to the three students achieving the highest combined average in PHYS\\*2330 (Electricity and Magnetism I) and PHYS\\*2240 (Thermal Physics) in the previous academic semester."
		award_page = "https://www.physics.uoguelph.ca/copernicus-scholarships-physics"

	[[params.awards.award]]
		name = "College of Biological Sciences Dean’s Scholarship"
		year = "2020"
		description = "Awarded to those students demonstrating a high level of academic achievement. At the time that I was considered for this award, I was enrolled in the Biochemistry program through the College of Biological Sciences."
		award_page = "https://www.uoguelph.ca/ada-cbs/current-undergraduates/awards-and-financial-information/deans-scholarships"

[[params.projects]]
	[[params.projects.project]]
		name = "Kilonova Modelling for Neutron Star Merger Simulations"
		description  = "Implementing numerical models to predict kilonova light curves due to r-process nucleosynthesis accompanying the output of neutron start collision simulations. Exploring the results of various ejecta models. Working with Prof. Daniel Siegel's group at the University of Guelph and Perimeter Institute."
		date = "May 2021 - Current"
		project_page = ""
		code_link = ""
		blog_link = ""

 [[params.projects.project]]
		name = "Processing IR Microscope Data of Accelerated-Aged PEX-a pipe"
		description  = "Independently planned, built, documented and maintained a Python script for processing over 14,000 infrared spectra on PEX pipes alongside categorical information on samples. Database structure is ideal for streamlining analysis, visualization, and the addition of new data. Worked with Prof. John R. Dutcher's group at the University of Guelph."
		date = "May 2020 - April 2021"
		project_page = ""
		code_link = ""
		blog_link = ""
